### ISSUE TITLE
Create a contribution guideline

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-element-skeleton#146]
Create a list of quality requirements for external contributions as CONTRIBUTION.MD, for example.
Mention that that number of requirements met speeds up the process of merging external PR.

Components:
- [ ] vaadin-button
- [ ] vaadin-checkbox
- [ ] vaadin-combo-box
- [ ] vaadin-context-menu
- [ ] vaadin-date-picker
- [ ] vaadin-dialog
- [ ] vaadin-dropdown-menu
- [ ] vaadin-form-layout
- [ ] vaadin-grid
- [ ] vaadin-item
- [ ] vaadin-list-box
- [ ] vaadin-notification
- [ ] vaadin-progress-bar
- [ ] vaadin-radio-button
- [ ] vaadin-split-layout
- [ ] vaadin-tabs
- [ ] vaadin-text-field
- [ ] vaadin-upload
- [ ] vaadin-ordered-layout

**Comment by web-padawan** [comment]
Applied to all components.
