### ISSUE TITLE
Do not run tests in shadydom

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-element-skeleton#178]
- It duplicates the number of tests to run
- It does not guarantee that polyfill works correctly as demonstrated in https://github.com/vaadin/vaadin-grid/issues/1389
- Grid already skips these tests

Discussed in thread https://vaadin.slack.com/archives/G6QQTHU8Z/p1540392138000100

**Comment by web-padawan** [comment]
Will be done as part of #207 while also moving away from `wct` towards `karma`.
