### ISSUE TITLE
README_CREATE_NEW.md: automated `perl`-based search-replace commands produce imperfect results

### ISSUE THREAD

**Issue by lkraav** [vaadin/vaadin-element-skeleton#183]
We're a bit overloaded right now to post a deep analysis, but for one teammate quote:

> This command also changed the “vaadin-element-mixin” inside bower.json and the bower install operation got stuck.

Also, `perl` may not be easily available on Windows platforms. Perhaps `sed` would be a better choice?

Summary: new element instructions need further iteration in several spots.

**Comment by web-padawan** [comment]
Yeah, that's a long lasting issue affecting us since the time when that mixin has been added. 
We should definitely fix the replacement snippets.

**Comment by web-padawan** [comment]
This should be no longer a problem because we changed to `vaadin-component`.
