### ISSUE TITLE
Expose an ES "module" entrypoint in package.json manifest

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-element-skeleton#189]
https://www.pikapkg.com/packages/?q=@vaadin/vaadin-grid

![image](https://user-images.githubusercontent.com/6059356/49795000-9471fd00-fd41-11e8-84a4-44e0c905ad63.png)

Learn more: https://www.pikapkg.com/packages/about/

**Comment by web-padawan** [comment]
I recall the conversation with Fred (ex-Polymer team member and creator of Pika) and Justin Fagnani regarding the `"module"` field. Will try to find it and link here.

**Comment by web-padawan** [comment]
Will be done in #207 as now we are finally converting codebase to ES modules.
