### ISSUE TITLE
Consider restoring package-lock.json

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-element-skeleton#193]
Originally reported as part of vaadin/vaadin-select#178

`.npmrc` has `package-lock.json=false` set. This is unexpected behaviour. npm recommends that `package-lock.json` is committed to git repository. It also stops `npm audit` from running.

Note from myself: this would allow us to run `npm ci` in Travis, which is expected to be a bit faster.

**Comment by limonte** [comment]
`package-lock.json` is a joke:

- https://stackoverflow.com/q/45022048/1331425
- https://github.com/npm/npm/issues/17979

Here's the thing

### Current behavior

```
git clone <any_repo_with_package_lock_json>
npm install

git status

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package-lock.json

```

`package-lock.json` is changed, nonsense which only developers of `npm/cli` can understand :) Other people seem to be [confused](https://github.com/npm/npm/issues/18103#issuecomment-370401935):

![image](https://user-images.githubusercontent.com/6059356/46935793-edd0ef00-d064-11e8-877c-456a425b50f2.png)

---

If `lock` file is needed for any reason (e.g. security, consistency), then `yarn.lock` is the way to go.

**Comment by web-padawan** [comment]
I think the issue you are mentioning has been fixed at some point, but we need to double check.
At least we should update Node to 10.14 LTS in the same scope, to pick up npm ^6.4.0

**Comment by limonte** [comment]
> I think the issue you are mentioning has been fixed at some point, but we need to double check.
At least we should update Node to 10.14 LTS in the same scope, to pick up npm ^6.4.0

Nope.

```sh
 }> npm -v
6.4.1
}> git clone git@github.com:Polymer/polymer.git
}> npm install
}> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```
