### ISSUE TITLE
Initializing a new component repository should be more automated

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-element-skeleton#209]
When setting up [vaadin-date-time-picker](https://github.com/vaadin/vaadin-date-time-picker) repository I used the [new-element script](https://gist.github.com/manolo/9c0432f29b8fdef5325f17cf3c9c301b) (which can be found linked from our [internal team wiki](https://github.com/vaadin/components-team-tasks/wiki/Scripting-snippets#creating-a-new-element).

You can see the result of that in the [initial commit](https://github.com/vaadin/vaadin-date-time-picker/commit/5811ec9cdb410f92c0231ebfc0e15c81b7061bed) but after that I still had to do some minor renames and adjustments manually in this [second commit](https://github.com/vaadin/vaadin-date-time-picker/commit/ea2ceb54ef7798201cedeb3b17cdea049955fa7f) and [this](https://github.com/vaadin/vaadin-date-time-picker/commit/ebc9383b5522f31d89e24483c22ec9d6305efe33)

- rename `ElementDemo` to `[ElementName]Demo` (`DateTimePickerDemo` in this case)
- write names/titles in `demo/demos.json` and `demo/index.html` in a slightly different format. I compared to how those are written in vaadin-date-picker, vaadin-time-picker and some other component. I think currently these are not even in the same format in all existing components, maybe need to decide what is the best default for new stuff atm.
- rename element class to remove `Vaadin` prefix (`VaadinDateTimePicker` to `DateTimePicker`)
- rename the directory that contains the visual test reference screenshots (`vaadin-element` to `vaadin-date-time-picker`), otherwise running the visual tests doesn't find the reference images.

We should modify the `vaadin-element-skeleton` and/or the `new-element` script (as necessary) to make it so the above points also go right automatically so you can just start implementing the component MVP right after running the `new-element` script.

Maybe the `new-element` script should be part of this `vaadin-element-skeleton` repository in the root instead of being a separate Gist? Maybe it would make sense to slightly modify it so you can have  this repository cloned, but running the init script from there would create the new element in a separate directory (e.g. specifying the output directory along with the new element name as a parameter) and the script could remove itself from the newly initialized repo.

**Comment by web-padawan** [comment]
Closing as new components are now created in the monorepo and the script is not used anymore.
