### ISSUE TITLE
Add an explicit link to documentation

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-element-skeleton#23]
Currently, there’s no mention of documentation in the readme. We should have a clear title or link that says “Documentation” or “Docs” to point people in the right direction. Even though in our case the “Live Demo” is the main learning material, users are most likely looking for documentation instead of demos when they run into some problem how to use the component.

**Comment by tomivirkki** [comment]
Fixed in https://github.com/vaadin/vaadin-element-skeleton/commit/2f29c1cc6efb514cf6b84db3c770db252aad0486
