### ISSUE TITLE
Navigation is broken

### ISSUE THREAD

**Issue by anssit** [vaadin/vaadin-element-skeleton#25]
Clone repo and npm install && bower install && polyserve will result in the following:

<img width="710" alt="screen shot 2017-03-06 at 11 40 47" src="https://cloud.githubusercontent.com/assets/16914037/23606067/cf6781f4-0267-11e7-8380-809df2993cc3.png">

**Comment by manolo** [comment]
@anssit  service workers messages are not related with this issue.
Those are because you have tested in local host some app that registers a service-worker, try to unregister it via the app tab of chrome dev tools console
