### ISSUE TITLE
Add CSS linting

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-element-skeleton#6]
Judging from the late comments from @platosha about the CSS syntax corrections in https://github.com/vaadin/vaadin-grid/pull/583, it seems like we would benefit from CSS linting that would force us to conform to a certain set of rules for CSS.

**Comment by limonte** [comment]
You just read my mind :+1: We definitely should perform the CSS linting automatically.

**Comment by limonte** [comment]
Unfortunately, we can't automatically handle cases like this one:

```css
vaadin-grid {
  --vaadin-grid-cell: {
    ...
  }; 
/* ^ we can't catch this semicolon if it's missing */
}
```

Reason is that Polymer has its own way to use mixins: https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-mixins

Example:

```css
:host {
  --my-toolbar-title-theme: {
    color: green;
  };
/* ^ */
}
```

From Polymer's POV `--my-toolbar-title-theme` is a mixin and there should be a semicolon after it. 
From CSS's POV it's just a nested block and there shouldn't be any trailing semicolon after it.

**Comment by limonte** [comment]
I just added the CSS linter to the vaadin-grid (which has a lot of CSS) to test and discuss approach: https://github.com/vaadin/vaadin-grid/pull/612

As you can see, despite the fact that there's a lot of CSS, a number of errors is minimal. Each member of the Elements team has a good sense for CSS code, so maybe CSS linter is not so necessary as JS linter.

**Comment by jouni** [comment]
Have you tried the linting some other element, like the date-picker? I think the grid has probably gotten the most amount of reviews by the team (and has been pretty stable for a long time now), so the code might be in a better shape because of that.

**Comment by limonte** [comment]
> Have you tried the linting some other element, like the date-picker?

For the date-picker there's even smaller number of CSS errors: https://github.com/vaadin/vaadin-date-picker/compare/fix/css-lint?expand=1

**Comment by limonte** [comment]
I created [stylelint-config-vaadin](https://github.com/vaadin/stylelint-config-vaadin), now there's no need to copy-paste all rules to each component and `.stylelintrc` looks as simple as:

```js
{
  "extends": "stylelint-config-vaadin"
}
```
