### ISSUE TITLE
Downplay the importance of Polymer in the description

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-element-skeleton#67]
Currently, the description text says “<vaadin-element> is a Polymer 2 element for—”. Stating that we use Polymer to build our web components should be downplayed, and instead, we should be promoting that our elements are web components.

Polymer should still probably be mentioned somewhere in the readme/API docs, to improve SEO, but not in the first paragraph.

This can make our elements less intimidating perhaps, and if we ever switch away from Polymer, it causes a less drastic change in the visible description text.

**Comment by web-padawan** [comment]
Fixed in #118

**Comment by tomivirkki** [comment]
The readme changes are applied to components' p3-preview branches. Once V10 is out, we can start merging the p3-branches to masters and get this finished.
