### ISSUE TITLE
Add a note to README about PRs with new features

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-element-skeleton#70]
Add a note to `README` PR section that PRs with new features will be accepted only to the latest versions of our components. Only bug fixes will be accepted to the previous versions.

**Comment by web-padawan** [comment]
Assuming V14 will have minor releases, this statement is no longer true (so that we would probably add features to `vaadin-14` branches at some point). And the README entry might be confusing. 

Also, we haven't received much external PRs with new features lately. If we do, let's reconsider this.
